Switch back to using `pyproject.toml` to build
openforcefield/openff-nagl pull request #169
Opened 2024-12-17 15:46 UTC by mattwthompson

Fixes #168

Changes made in this Pull Request:

 - Move `setup.py` build config to `pyproject.toml`
 - Move a few simple config settings to `pyproject.toml`
 - Remove LGTM config, since it appears to not be used

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

2025-01-03 19:52 UTC, mattwthompson commented
It's hard for me to reason through the failing tests - the package appears to build fine when used in the conventional CI so it's weird that it's not working in the "build from X" workflows

2025-01-13 19:57 UTC, lilyminium requested changes
Not sure what's going on with the conda build at the moment, since the conda test should be building from an environment file but is erroring on a lack of pytorch -- I'll kick the test again.

2025-01-13 19:57 UTC, lilyminium commented on .github/workflows/gh-ci.yaml
> +        python -m pip install .
```suggestion
        python3 -m pip install --upgrade build
```

This command used to build a tarball (`sdist`) for distribution, I believe this should be the new syntax.

2025-01-13 20:44 UTC, lilyminium commented on .github/workflows/gh-ci.yaml
> +        python3 -m pip install --upgrade build
```suggestion
        python3 -m pip install --upgrade build
        python3 -m build
```

Ahh forgot a line

2025-01-13 22:11 UTC, lilyminium commented
Check is now failing due to https://github.com/pypa/setuptools/issues/2522 where the tarball is now created with underscores instead of hyphens. I *think* that this should have been correct behaviour overall, although it is slightly disconcerting to have the name set to `openff-nagl` and the tarball be `openff_nagl`.

2025-01-14 01:27 UTC, lilyminium commented
Both the pypi and conda build checks are now passing.... @mattwthompson could I punt this back to you for a quick re-review of my changes and a sense-check that having an underscore in the tarball is fine? I'll dismiss mine.

The RTD failure is unrelated to this PR, will open a new issue for that.

2025-01-14 01:27 UTC, lilyminium approved these changes

2025-01-14 07:49 UTC, lilyminium commented on setup.cfg
>  [isort]
Thanks so much for cleaning this up!

2025-01-14 20:27 UTC, mattwthompson commented on .github/workflows/gh-ci.yaml
> +        python3 -m pip install --upgrade build
Wow, didn't expect this at all

2025-01-14 20:44 UTC, mattwthompson commented on .pre-commit-config.yaml
> +      - id: flake8
None of these are actually run, but pointing to a branch is taboo so as least that's updated

2025-01-14 20:44 UTC, mattwthompson commented on .github/workflows/gh-ci.yaml
> +        test -n "${DISTRIBUTION}" || { echo "no distribution dist/openff_nagl-*.tar.gz found"; exit 1; }
This seems fine to me

2025-01-15 14:21 UTC, merged